### ISSUE TITLE
Magic Numbers in experiment.py

### ISSUE THREAD

**Issue by jrieffel** [ai-honzik/sr2020#6]
`ME = cvt_map_elites.mapelites( 2, 5*number_of_materials, n_niches=100,
                                   max_evals=500, params=px,
                                   exp_folder=dirs["mapelites"] + "/" )`

The first two numbers are magic numbers, and also have to be independently changed in a couple of other spots in SimulationManager.  (Also what does the first argument correspond to? number of fitness dimensions?)

**Comment by dolejs-jan** [comment]
Yes, this one I have on the list. First argument corresponds to number of dimensions for descriptor (eg. `delta x, delta y`).

**Comment by dolejs-jan** [comment]
Got rid of magical consts for `dim_map` and `dim_x`.
